import type { Metadata } from "next";
import { Diplomata } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { DINRoundProMedi } from "@/config/font";
import Navbar from "@/components/NavBar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import ClientProvider from "@/components/provider/client-provider";
import TRPCProvider from "@/components/provider/trpc-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/auth";

const inter = Diplomata({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  console.log(`session`, session);

  return (
    <html lang="en">
      {" "}
      <body
        className={cn(
          "min-h-screen scroll-smooth bg-background font-sans antialiased",
          DINRoundProMedi.className,
        )}
      >
        <Toaster />
        <TRPCProvider>
          <TooltipProvider>
            <ClientProvider session={session}>{children}</ClientProvider>
          </TooltipProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
