name: Prisma CLI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prisma:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm install
      - name: Run Prisma Commands
        run: npm run prisma-cli -- -g -f
